'use strict';
const $=id=>document.getElementById(id);
const mobile=()=>window.matchMedia('(max-width:560px)').matches;
const reduced=window.matchMedia('(prefers-reduced-motion:reduce)').matches;
const map=L.map('map',{zoomControl:false,attributionControl:true,minZoom:1,maxZoom:8,zoomSnap:.25,worldCopyJump:false,maxBounds:[[-80,-190],[85,190]],maxBoundsViscosity:.8});
map.attributionControl.setPrefix('<a href="https://leafletjs.com" target="_blank" rel="noopener">Leaflet</a>');
map.attributionControl.addAttribution('<a href="https://github.com/johan/world.geo.json" target="_blank" rel="noopener">Mapa: Natural Earth</a>');
const countryLayer=L.geoJSON(WORLD,{style:{color:'#b8cbd4',weight:.7,fillColor:'#fafbfa',fillOpacity:1},interactive:false}).addTo(map);
for(let lat=-60;lat<=60;lat+=30)L.polyline([[lat,-180],[lat,180]],{color:'#cbdbe2',weight:.6,opacity:.65,interactive:false}).addTo(map);
for(let lng=-180;lng<=180;lng+=30)L.polyline([[-75,lng],[82,lng]],{color:'#cbdbe2',weight:.6,opacity:.65,interactive:false}).addTo(map);
const markers=L.layerGroup().addTo(map),labels=L.layerGroup().addTo(map);
let selected=null,lastTrigger=null;
function worldView(){map.fitBounds([[-57,-145],[72,170]],{paddingTopLeft:[20,mobile()?165:110],paddingBottomRight:[20,45],animate:false});}
function render(){markers.clearLayers();labels.clearLayers();const groups=[];
for(const s of SITES){const point=map.latLngToLayerPoint([s.lat,s.lng]);let g=groups.find(g=>g.point.distanceTo(point)<31&&s.id!==selected&&!g.items.some(x=>x.id===selected));if(g){g.items.push(s)}else groups.push({point,items:[s]});}
for(const g of groups){const count=g.items.length;const s=g.items[0];const coords=count===1?[s.lat,s.lng]:[g.items.reduce((a,s)=>a+s.lat,0)/count,g.items.reduce((a,s)=>a+s.lng,0)/count];const m=L.marker(coords,{icon:L.divIcon({className:'site-marker'+(s.id===selected?' selected':''),html:count===1?'<span class="pin"></span>':`<span class="cluster">${count}</span>`,iconSize:[44,44],iconAnchor:[22,22]}),keyboard:true,title:count===1?s.name:`${count} sítios: ${g.items.map(x=>x.name).join(', ')}`,alt:count===1?s.name:`Ampliar grupo de ${count} sítios`,riseOnHover:true}).addTo(markers);
m.on('click',()=>{if(count>1){map.fitBounds(g.items.map(s=>[s.lat,s.lng]),{padding:[70,70],maxZoom:6,animate:!reduced});}else{lastTrigger=m.getElement();openSite(s.id);}});if(count===1)m.bindTooltip(s.name,{direction:'top',offset:[0,-13]});}
const oceans=[['Oceano Pacífico',10,-133],['Oceano Atlântico',5,-32],['Oceano Índico',-24,79]];
if(map.getZoom()<3.2)for(const [name,lat,lng]of oceans)L.marker([lat,lng],{interactive:false,keyboard:false,icon:L.divIcon({className:'ocean-label',html:name,iconSize:[180,20],iconAnchor:[90,10]})}).addTo(labels);
if(map.getZoom()>=3){const names=new Intl.DisplayNames(['pt-BR'],{type:'region'});countryLayer.eachLayer(layer=>{const b=layer.getBounds();if(!map.getBounds().intersects(b))return;const size=map.latLngToLayerPoint(b.getNorthEast()).distanceTo(map.latLngToLayerPoint(b.getSouthWest()));if(size<65)return;let name=layer.feature.properties.name;const known={'Brazil':'Brasil','France':'França','Spain':'Espanha','United Kingdom':'Reino Unido','Egypt':'Egito','Greece':'Grécia','Italy':'Itália','Turkey':'Turquia','China':'China','India':'Índia','Iraq':'Iraque','Iran':'Irã','Australia':'Austrália','Mexico':'México','Peru':'Peru','Chile':'Chile','Argentina':'Argentina','Russia':'Rússia','United States of America':'Estados Unidos','Canada':'Canadá','South Africa':'África do Sul','Algeria':'Argélia','Saudi Arabia':'Arábia Saudita','Indonesia':'Indonésia','Pakistan':'Paquistão'};L.marker(b.getCenter(),{interactive:false,keyboard:false,icon:L.divIcon({className:'country-label',html:known[name]||name,iconSize:[150,15],iconAnchor:[75,7]})}).addTo(labels);});}}
function openSite(id){const s=SITES.find(x=>x.id===id);if(!s)return;selected=id;$('site-select').value=id;$('card-title').textContent=s.name;$('card-description').textContent=s.description;$('card-region').textContent=s.region;$('card-index').textContent=String(SITES.indexOf(s)+1).padStart(2,'0')+' / '+SITES.length;$('card-age').textContent=s.age;$('card-country').textContent=s.country;$('card-period').textContent=s.period;$('card-note').textContent=s.note;$('source-link').href=s.source;$('image-link').href=s.photoSource||s.source;$('image-credit').textContent=s.credit||'Wikimedia Commons · consulte a autoria e a licença no link da fotografia.';
$('photo-error').hidden=true;$('photo-fallback').href=s.photoSource||s.source;$('site-photo').onerror=()=>{$('photo-error').hidden=false;};$('site-photo').alt=s.photoCaption||s.name+' — fotografia do sítio arqueológico';$('site-photo').src=s.photo||'';$('site-card').hidden=false;$('site-card').scrollTop=0;document.body.classList.add('card-open');
const zoom=Math.max(map.getZoom(),mobile()?3:3.25);const p=map.project([s.lat,s.lng],zoom);p.x+=mobile()?0:190;p.y+=mobile()?map.getSize().y*.23:0;map.setView(map.unproject(p,zoom),zoom,{animate:!reduced});render();$('status').textContent=s.name+', '+s.country+', aproximadamente '+s.age;$('card-title').focus({preventScroll:true});}
function closeCard(){selected=null;$('site-card').hidden=true;document.body.classList.remove('card-open');$('site-select').value='';render();$('site-select').focus({preventScroll:true});}
SITES.slice().sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name+' · '+s.country;$('site-select').appendChild(o);});
$('site-select').addEventListener('change',e=>{if(e.target.value)openSite(e.target.value)});$('close-card').onclick=closeCard;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)closeCard();});$('zoom-in').onclick=()=>map.zoomIn();$('zoom-out').onclick=()=>map.zoomOut();$('reset').onclick=()=>{if(selected)closeCard();worldView();};map.on('zoomend moveend',render);window.addEventListener('resize',()=>{map.invalidateSize();if(!selected)worldView();});worldView();render();
